version: '3'

services:
  database:
    image: postgres
    container_name: riderize-challenge
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/database-docker:/var/lib/postgresql/data